# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotank',
            options={'verbose_name': 'Hydra', 'verbose_name_plural': 'Hydra'},
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='day_min_light',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='m',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='mh',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='night_end',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='night_max_light',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='night_start',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='x',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='iotank',
            name='xh',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='h',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='l',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='t1',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='t2',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='uv',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='do',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Dissolved Oxygen'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ec',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Conductivity'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='orp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='ORP'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='rtd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Waterproof Temp'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('E', 'E-mail')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notices',
            name='type',
            field=models.CharField(choices=[('I', 'Hydra Emergency')], max_length=1),
        ),
    ]
