# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20180619_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='orp',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='ORP'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='ph',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='pH'),
        ),
    ]
