# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20180620_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotank',
            name='ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='iotank',
            name='rssi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='RSSI'),
        ),
    ]
